#example configuration file - follow this structure to define a classification run

#arguments definitions
######################
#load_model: boolean, should an SVM model be loaded (otherwise needs to be trained)
#if load_model: True, ignored otherwise:
#    model_file: str, path to model file

#tracklet_dataset: str, which dataset is to be classified
#    check load_events.py for options
#division: how to divide the detector up
#    check ./find_detector_region.py for options
#region_id: str, options depend on division chosen
#data_scaler: str, how to scale data
#    check data_transform in ./main.py fo options
#add_to_tracklet: list or None, which properties are to be added to data features
#    check add_physics_to_tracklet in ./main.py for options
#num_test: int, how many events to test on
#num_train: int, how many events to train on (or how many were used if load_model: True)
#class_weight: dict, what weights are to be applied to each of the two classes
#classical: boolean, is kernel estimated classically
#if classical: True, ignored otherwise:
#    gamma: float, gamma parameter of the rbf kernel (if classical: True)
#    C_class: float, C parameter for classical kernel
#if classical: False, ignored otherwise:
#    alpha: float, alpha parameter for quantum kernel
#    C_quant: float, C parameter for quantum kernel
#    single_mapping: int, which mapping to choose for single qubit operations
#        check ../quantum_circuit/param_U_gate.py for options
#    pair_mapping: int, which mapping to choose for two-qubit operations
#        check ../quantum_circuit/param_U_gate.py for options
#    interaction: str, what two-qubit gate to use
#        check ../quantum_circuit/param_U_gate.py for options
######################

load_model: False
model_file: model_from_config1.sav
#tracklet_dataset: triplet
#division: new_phi
#region_id: '0'
data_scaler: global
add_to_tracklet: null
num_test: 1
num_train: 1
class_weight: 
  0: 1.0
  1: 1.0
classical: True
gamma: 1
C_class: 1.0e+6
alpha: 0.1
C_quant: 1.0e+6
single_mapping: 1
pair_mapping: 1
interaction: YY
circuit_width: 6
